select * from FACTURAS;
SELECT * FROM ITEMS_FACTURAS;

SELECT F.DNI, F.FECHA_VENTA, IFa.CANTIDAD FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;


SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, IFa.CANTIDAD FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

/*CANTIDAD DE VENTAS POR MES PARA CADA CLIENTE*/
SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
GROUP BY 
F.DNI, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y");

/*LIMITE DE VENTAS POR CLIENTE*/
SELECT * FROM tabla_de_clientes;
