/*CREANDO UNA TABLA

CREATE TABLE <nombre de la tabla>(
<nombre del campo 1> <tipo de campo N> <definir si campo 1 es o no NULL>,
(...)
<nombre del campo N> <tipo de campo N> <definir si campo 1 es o no NULL>,
PRIMARY KEY (<campo(s) separado(s) por  ",">)
);

DROP TABLE <nombre de la tabla>; */

USE VENTAS_JUGOS;
CREATE TABLE TB_VENDEDOR(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
DE_VACACIONES BIT(1) NULL,
PRIMARY KEY(MATRICULA)
);

CREATE TABLE TB_PRODUCTO(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMAÑO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECIO_LISTA float NULL,
PRIMARY KEY(CODIGO)
);

CREATE TABLE CLIENTES(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) DEFAULT NULL,
DIRECCION VARCHAR(150) DEFAULT NULL,
BARRIO VARCHAR(50) DEFAULT NULL,
CIUDAD VARCHAR(50) DEFAULT NULL,
ESTADO VARCHAR(45) DEFAULT NULL,
CP VARCHAR(8) DEFAULT NULL,
FECHA_NACIMIENTO date DEFAULT NULL,
EDAD INT DEFAULT NULL,
SEXO VARCHAR(1) DEFAULT NULL,
LIMITE_CREDITO FLOAT DEFAULT NULL,
VOLUMEN_COMPRA FLOAT DEFAULT NULL,
PRIMERA_COMPRA BIT(1) DEFAULT NULL,
PRIMARY KEY (DNI)
);
DROP TABLE CLIENTES;

/* TABLA CREADA CON EL ASISTENTE SCRIPT COPIADO
CREATE TABLE `ventas_jugos`.`facturas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `FECHA` DATE NULL,
  `DNI` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `IMPUESTO` FLOAT NULL,
  PRIMARY KEY (`NUMERO`)); */


