CREATE TABLE TB_DEFAULT(
ID INT AUTO_INCREMENT,
DESCRIPCION VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(100) NULL,
CIUDAD VARCHAR(50) DEFAULT 'Monterrey',
FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY (ID)
);

INSERT INTO tb_default
(DESCRIPCION, DIRECCION, CIUDAD, FECHA_CREACION)
values ('CLIENTE X', 'CALLE SOL, 525', 'CANCUN', '2021-01-01');

SELECT * FROM TB_DEFAULT;

INSERT INTO tb_default
(DESCRIPCION/*, DIRECCION, CIUDAD, FECHA_CREACION*/)
values ('CLIENTE Y');