SELECT * FROM JUGOS_VENTAS.TABLA_DE_CLIENTES;
SELECT * FROM ventas_jugos.TB_CLIENTE;

SELECT DNI, NOMBRE, DIRECCION_1 AS DIRECCION, BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO AS FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, 
VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA, PRIMERA_COMPRA
 FROM JUGOS_VENTAS.TABLA_DE_CLIENTES
 WHERE DNI NOT IN (SELECT DNI FROM TB_CLIENTE);
 
INSERT INTO TB_CLIENTE
	SELECT DNI, NOMBRE, DIRECCION_1 AS DIRECCION, BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO AS FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, 
	VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA, PRIMERA_COMPRA
	FROM JUGOS_VENTAS.TABLA_DE_CLIENTES
WHERE DNI NOT IN (SELECT DNI FROM TB_CLIENTE);

SELECT * FROM ventas_jugos.TB_CLIENTE;

use ventas_jugos;
SELECT * FROM ventas_jugos.TB_vendedor;